<?php

/**
 * @file
 * Contains as_book.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_book_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_book module.
    case 'help.page.as_book':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a Book reservation application for the website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function as_book_theme($existing, $type, $theme, $path) {

  return [
    'book_listing' => [
      'render element' => 'elements',
    ],
  ];











  
}
